---
apiVersion: phenix.sandia.gov/v2
kind: Scenario
metadata:
  name: ${BRANCH_NAME}
  annotations:
    topology: ${BRANCH_NAME}
spec:
  apps:
    - name: tap
      metadata:
        taps:
          - bridge: phenix
            vlan: MGMT
            ip: 172.16.0.1/24
            externalAccess:
              enabled: true
    - name: scorch
      metadata:
        components:
          - name: exp-break
            type: break
          - name: erspan-test
            type: erspan
            metadata:
              local_bridge: test
              local_ip: 192.168.1.1
              remote_ip: 192.168.1.2
              excluded_vlans:
                - MGMT
        runs:
          - name: mine
            start:
              - exp-break
            configure:
              - erspan-test
            cleanup:
              - erspan-test
